(batch* IrisCoreLispBase.clp)
(batch* IrisCoreLispConstantDeclaration.clp)
(batch* IrisCoreLispLinkRegisterMacros.clp)
(batch* IrisCoreLispPredicateRegisterMacros.clp)
(batch* IrisCoreLispStackOperations.clp)
